CollectWuFuWeChatSmallProcess/Controllers/MerchantController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Newtonsoft.Json;
using CollectWuFuWeChatSmallProcess.AppData;
using CollectWuFuWeChatSmallProcess.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Tools.Models;
using Tools.Response;
using Tools.Response.Json;
using We7Tools;
using We7Tools.Extend;
using System.Net.Http.Headers;
using ConfigData;

namespace CollectWuFuWeChatSmallProcess.Controllers
{
    public class MerchantController : BaseController<MerchantData, CompanyModel>
    {
        private IHostingEnvironment hostingEnvironment;

        public MerchantController(IHostingEnvironment environment) : base(true)
        {
            hostingEnvironment = environment;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            //var thList = GetOrderViewList();
            return View();
        }

        //private object GetOrderViewList()
        //{
        //    return thisData.GetOrderViewList(HttpContext.Session.GetUniacID());
        //}

        public IActionResult Settings()
        {
            var companyModel = thisData.GetCompanyModel(HttpContext.Session.GetUniacID());
            if (companyModel == null)
            {
                companyModel = new CompanyModel { ProcessMiniInfo = new ProcessMiniInfo() };
            }
            return View(new ManageViewModel
            {
                ProcessMiniInfo = companyModel.ProcessMiniInfo,
                Company = companyModel
            });
        }
        public IActionResult AccountInfo()
        {
            var fblist = thisData.GetAccountList(HttpContext.Session.GetUniacID());
            return View(fblist);
        }
        public IActionResult ProcessMiniZipDownload()
        {
            if (!HttpContext.Session.HasWe7Data())
            {
                return RedirectToAction(nameof(Index), "Error", new { errorType = ErrorType.ErrorNoUserOrTimeOut });
            }
            try
            {
                string fileUrl;
                ProcessMiniTool.GetProcessMiniZipPath(HttpContext.Session, out fileUrl);
                var fileByteArray = System.IO.File.ReadAllBytes(fileUrl);
                var fileName = Path.GetFileName(fileUrl);
                System.IO.File.Delete(fileUrl);
                return File(fileByteArray, "application/vnd.android.package-archive", fileName);
            }
            catch (Exception e)
            {
                e.Save();
                return RedirectToAction("Index", "Error");
                //throw;
            }
        }

        public IActionResult SetCompanyInfo()
        {
            try
            {
                using (var streamReader = new StreamReader(Request.Body))
                {
                    var json = streamReader.ReadToEnd();
                    var company = JsonConvert.DeserializeObject<CompanyModel>(json);
                    company.uniacid = HttpContext.Session.GetUniacID();
                    thisData.SaveCompanyInfo(company);
                }
                return this.JsonSuccessStatus();
            }
            catch (Exception e)
            {
                e.Save();
                return this.JsonErrorStatus();
            }
        }
        public IActionResult SetQiNiu()
        {
            try
            {
                string json = new StreamReader(Request.Body).ReadToEnd();
                QiNiuModel qiNiuModel = JsonConvert.DeserializeObject<QiNiuModel>(json);
                thisData.SetQiNiu(HttpContext.Session.GetUniacID(), qiNiuModel);
                return this.JsonSuccessStatus();
            }
            catch (Exception)
            {
                return this.JsonErrorStatus();

            }
        }

        public IActionResult SavePic(PicType picType)
        {
            try
            {
                long size = 0;
                var files = Request.Form.Files;
                var file = files[0];
                var filename = ContentDispositionHeaderValue
                                      .Parse(file.ContentDisposition)
                                      .FileName
                                      .Trim('"');
                var uniacid = HttpContext.Session.GetUniacID();
                string saveDir = $@"{MainConfig.BaseDir}{MainConfig.TempDir}{uniacid}/";
                if (!Directory.Exists(saveDir))
                {
                    Directory.CreateDirectory(saveDir);
                }
                string exString = filename.Substring(filename.LastIndexOf("."));
                string saveName = Guid.NewGuid().ToString("N");
                filename = $@"{saveDir}{saveName}{exString}";

                size += file.Length;
                using (FileStream fs = System.IO.File.Create(filename))
                {
                    file.CopyTo(fs);
                    fs.Flush();
                }
                thisData.SavePic(picType, uniacid, filename);
                return this.JsonSuccessStatus();
            }
            catch (Exception)
            {
                return this.JsonErrorStatus();
            }
        }
    }
}

CollectWuFuWeChatSmallProcess/Views/Shared/_Layout.cshtml
@using We7Tools.Extend;
@{string title = "招财神后台"; }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @title</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class='navbar navbar-inverse navbar-fixed-top @(CollectWuFuWeChatSmallProcess.Views.ViewConst.CheckRout(ViewData,CollectWuFuWeChatSmallProcess.Views.RoutType.登录)||CollectWuFuWeChatSmallProcess.Views.ViewConst.CheckRout(ViewData,CollectWuFuWeChatSmallProcess.Views.RoutType.错误)?"hidden":"")'>

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Merchant" asp-action="Index" class="navbar-brand">@title</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class='@(CollectWuFuWeChatSmallProcess.Views.ViewConst.CheckRout(ViewData,CollectWuFuWeChatSmallProcess.Views.RoutType.中奖记录)?"active":"")'><a asp-area="" asp-controller="Merchant" asp-action="Index">@CollectWuFuWeChatSmallProcess.Views.RoutType.中奖记录.ToString()</a></li>
                    <li class='@(CollectWuFuWeChatSmallProcess.Views.ViewConst.CheckRout(ViewData,CollectWuFuWeChatSmallProcess.Views.RoutType.客户信息)?"active":"")'><a asp-area="" asp-controller="Merchant" asp-action="AccountInfo">@CollectWuFuWeChatSmallProcess.Views.RoutType.客户信息.ToString()</a></li>
                    <li class='@(CollectWuFuWeChatSmallProcess.Views.ViewConst.CheckRout(ViewData,CollectWuFuWeChatSmallProcess.Views.RoutType.系统管理)?"active":"")'><a asp-area="" asp-controller="Merchant" asp-action="Settings">@CollectWuFuWeChatSmallProcess.Views.RoutType.系统管理.ToString()</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - @title</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>